name: iOS 单独构建
on: workflow_dispatch

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: 安装 Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.41.7

      - run: flutter pub get
      - run: flutter build ios --release --no-codesign

      # 👇 直接打包成你要的名字
      - name: 打包成 IPA
        run: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r 沐瑶影视2.0.ipa Payload/

      # 👇 直接上传 .ipa 文件
      - name: 上传 IPA
        uses: actions/upload-artifact@v4
        with:
          name: 沐瑶影视2.0-iOS
          path: 沐瑶影视2.0.ipa
